import React from 'react';
import '../css/style.css';

export const metadata = {
  title: 'Create React App',
  description: 'Generated by create react app',
};

function RootLayout({ children }: {
    children: React.ReactNode;
  }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="bg-gray-50 font-inter tracking-tight text-gray-900 antialiased">
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
